name: on-push
on: [push]
jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: bahmutov/npm-install@v1
            - name: Typecheck
              run: yarn typecheck
            - name: Lint
              run: yarn lint
            - name: Test
              run: yarn test

